TYPO3:
  Flow:
    http:
      chain:
        'process':
          chain:
            'ajaxWidget':
              position: 'before routing'
              component: 'TYPO3\Fluid\Core\Widget\AjaxWidgetComponent'
    object:
      includeClasses:
        # FIXME: We need to exclude StandardVariableProvider because of it's constructor arguments that can't be proxied for some reason
        'namelesscoder.fluid' : ['(?!^NamelessCoder\\Fluid\\Core\\Variables\\StandardVariableProvider$)(^.*$).*']